stages:
    - build
    - test

docker_image_build:
    stage: build
    script:
        - docker login -u $docker_username -p $docker_password 
        - docker build -t ronik-portfolio:latest .

docker_run:
    stage: test
    script:
        - docker run -p 80:80 -d ronik-portfolio:latest

