image: docker:latest

services:
  - docker:dind

stages:
    - build
    - run
    

docker_image_build:
    stage: build
    script:
        - docker login -u $docker_username -p $docker_password 
        - docker build -t ronik-portfolio:latest .
        - docker images
    
docker_image_run:
    stage: run
    script:
        - docker compose up -d





